<?php

namespace Palicao\Bundle\RsvpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InitiativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitiativeRepository extends EntityRepository
{
}
