parameters:
#    palicao_key_value.example.class: Palicao\Bundle\KeyValueBundle\Example

services:
#    palicao_key_value.example:
#        class: %palicao_key_value.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
